D = 201
dx = 0.1
dy = dx
dt = 0.001
Gamma = 0.
B = 0.3
sigma = 15
Disp = 1 / (2 + (Gamma * dt))
Dism = (2 - (Gamma * dt))
dts = (dt / dx) * (dt / dx)
number_iterations = 24
number_steps_print_file = 1
output = "\\output\\"
